import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, ArrowUpRight, BadgeCheck, Headphones, MapPin, ShieldCheck, Sparkles, Truck, BookOpen, SearchCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ProductCard } from '@/components/site/ProductCard';
import { SectionHeading } from '@/components/site/SectionHeading';
import { products } from '@/data/products';
import { categories } from '@/data/categories';
import { cities } from '@/data/cities';
import { serviceAreas } from '@/data/serviceAreas';
import heroImage from '@/assets/hero-vape.jpg';

export const Route = createFileRoute('/')({
  head: () => ({ meta: [{ title: 'KOTA VAPE SHOP | Premium Product Information in Kota' }, { name: 'description', content: 'Explore adult-focused device and pod information, brand guides, and local support from KOTA VAPE SHOP.' }, { property: 'og:title', content: 'KOTA VAPE SHOP | Premium Product Information in Kota' }, { property: 'og:description', content: 'A curated informational catalog and product research resource based in Kota.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }),
  component: Home,
});
const features = [
  { title: 'Local perspective', text: 'Rooted in Kota, with a focus on clear and useful local support.', Icon: MapPin },
  { title: 'Authenticity first', text: 'A considered approach to product details and source verification.', Icon: ShieldCheck },
  { title: 'Human support', text: 'Helpful answers to general questions about products and formats.', Icon: Headphones },
  { title: 'Curated selection', text: 'A focused look at devices, pods, and brands worth researching.', Icon: Sparkles },
];
const reasons = [
  { title: 'Strict authenticity', text: 'We prioritize accurate information and encourage verification of product details.', Icon: BadgeCheck },
  { title: 'Discreet service', text: 'Straightforward, respectful support when you have a question.', Icon: ShieldCheck },
  { title: 'Expert consultation', text: 'Find clarity on formats, compatibility, and product research.', Icon: SearchCheck },
  { title: 'Premium selection', text: 'An edited catalog designed to make exploration easier.', Icon: Sparkles },
];
function Home() {
  return <>
    <section className="relative min-h-[600px] h-[min(75vh,760px)] flex items-center overflow-hidden bg-background"><img src={heroImage} width={1536} height={1024} alt="Dark studio photograph of a premium pod device" className="absolute inset-0 w-full h-full object-cover object-[62%_center] opacity-75"/><div className="absolute inset-0 bg-gradient-to-r from-background via-background/85 to-transparent"/><div className="page-container relative z-10 py-16"><div className="max-w-[600px]"><p className="eyebrow">Kota, Rajasthan · An adult-focused catalog</p><h1 className="font-display text-[clamp(4rem,8vw,8rem)] font-semibold leading-[0.85]">KOTA<br/><span className="text-primary">VAPE SHOP</span></h1><div className="w-16 h-px bg-primary my-7"/><p className="text-muted-foreground text-base md:text-lg leading-8 max-w-lg">A considered place to explore product formats, discover brands, and get clear information from a team rooted in Kota.</p><div className="flex flex-wrap gap-3 mt-9"><Button asChild size="lg" className="h-12 px-7 uppercase tracking-widest text-xs font-bold"><Link to="/shop" search={{ q: '', brand: '', category: '' }}>Explore catalog <ArrowRight/></Link></Button><Button asChild variant="outline" size="lg" className="h-12 px-7 uppercase tracking-widest text-xs font-bold bg-transparent"><Link to="/about">Our approach</Link></Button></div></div></div><div className="absolute bottom-5 left-5 lg:left-8 z-10 text-[10px] uppercase tracking-[0.25em] text-muted-foreground">01 / Discover the collection</div></section>
    <div className="overflow-hidden border-y border-border bg-primary py-3 text-primary-foreground"><div className="marquee-track text-[11px] uppercase font-bold tracking-[0.2em]">{Array.from({length: 4}).map((_, i) => <div key={i} className="flex shrink-0 gap-12 px-6"><span>Curated product research</span><span>✦</span><span>Authenticity-focused information</span><span>✦</span><span>Rooted in Kota</span><span>✦</span><span>General customer support</span><span>✦</span></div>)}</div></div>
    <section className="border-b border-border bg-surface"><div className="page-container grid grid-cols-2 lg:grid-cols-4">{features.map(({title,text,Icon}) => <div key={title} className="px-4 md:px-7 py-9 border-r border-b lg:border-b-0 border-border last:border-r-0"><Icon size={24} strokeWidth={1.4} className="text-primary mb-5"/><h3 className="font-display text-xl sm:text-2xl font-semibold">{title}</h3><p className="text-muted-foreground text-xs sm:text-sm leading-6 mt-2">{text}</p></div>)}</div></section>
    <section className="py-20 md:py-28 page-container"><SectionHeading kicker="The brands" title="Explore by brand" description="Distinct perspectives on the names and formats in our research catalog." link="/categories"/><div className="grid grid-cols-2 md:grid-cols-4 gap-3 md:gap-5">{categories.map((category, i) => <Link key={category.slug} to="/shop" search={{ q: '', brand: category.name, category: '' }} className="group relative aspect-[4/5] overflow-hidden border border-border bg-card"><img src={category.image} alt={`Illustrative ${category.name} category`} loading="lazy" className="w-full h-full object-cover opacity-80 transition-transform duration-500 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-background via-transparent to-transparent"/><span className="absolute top-4 left-4 text-[10px] tracking-widest text-primary">0{i+1} / 04</span><div className="absolute bottom-4 left-4 right-4"><p className="text-[10px] uppercase tracking-widest text-muted-foreground">{category.description}</p><div className="flex justify-between items-end mt-1"><h3 className="font-display text-2xl sm:text-3xl font-semibold">{category.name}</h3><ArrowUpRight size={20} className="text-primary"/></div></div></Link>)}</div></section>
    <section className="py-20 md:py-28 bg-surface"><div className="page-container"><SectionHeading kicker="The edit" title="Trending now" description="A closer look at formats and designs in our catalog." link="/shop"/><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 md:gap-5">{products.filter(p => p.featured).slice(0,4).map(p => <ProductCard key={p.id} product={p}/>)}</div></div></section>
    <section className="py-20 md:py-28 page-container"><SectionHeading kicker="The collection" title="Best sellers" description="Popular catalog entries to compare and research." link="/shop"/><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 md:gap-5">{products.filter(p => p.bestseller).slice(0,4).map(p => <ProductCard key={p.id} product={p}/>)}</div></section>
    <section className="bg-surface py-20 md:py-28"><div className="page-container grid lg:grid-cols-[.8fr_1.2fr] gap-10 lg:gap-24"><div><p className="eyebrow">Answers, simply</p><h2 className="section-title">A little more<br/><span className="text-primary">clarity.</span></h2><p className="mt-5 text-muted-foreground leading-7 max-w-sm">Straight answers to common questions about our catalog and how we approach product information.</p><Link to="/faq" className="inline-flex mt-7 gap-2 items-center text-xs text-primary uppercase tracking-widest">All FAQs <ArrowUpRight size={16}/></Link></div><div className="border-t border-border">{[['What is this catalog for?', 'Our catalog is an informational resource for adults researching product formats, brands, and compatibility.'], ['How do you approach authenticity?', 'We prioritize clear sourcing and encourage confirming any specific product information with our team.'], ['Can I ask about a specific brand?', 'Yes. Use the contact page to send a general inquiry about a brand or device format.'], ['Are products available to purchase online?', 'No. This website does not offer online purchases, checkout, or ordering.']].map(([q,a]) => <details key={q} className="group border-b border-border py-5"><summary className="cursor-pointer list-none flex justify-between items-center gap-4 font-display text-xl md:text-2xl marker:hidden">{q}<span className="text-primary font-sans text-xl group-open:rotate-45 transition-transform">+</span></summary><p className="text-sm text-muted-foreground leading-7 mt-4 pr-10">{a}</p></details>)}</div></div></section>
    <section className="grid lg:grid-cols-2 min-h-[480px] bg-secondary"><div className="overflow-hidden"><img src={heroImage} alt="Editorial studio view of a pod device" loading="lazy" className="w-full h-full min-h-[350px] object-cover object-right"/></div><div className="px-6 py-16 md:px-16 lg:px-20 flex flex-col justify-center"><p className="eyebrow">Featured review / The journal</p><h2 className="font-display text-4xl md:text-6xl leading-none font-semibold max-w-lg">The details behind a better-informed choice.</h2><p className="text-muted-foreground leading-7 mt-6 max-w-lg">From material finish to everyday form, we look beyond first impressions to understand what makes a product worth exploring.</p><Button asChild variant="outline" className="mt-8 w-fit bg-transparent uppercase tracking-widest text-xs"><Link to="/about">Read more <ArrowRight/></Link></Button></div></section>
    <section className="py-20 md:py-28 page-container"><SectionHeading kicker="Our principles" title="Why choose Kota Vape Shop"/><div className="grid grid-cols-2 lg:grid-cols-4 gap-3 md:gap-5">{reasons.map(({ title, text, Icon }) => <div key={title} className="border border-border bg-card p-5 md:p-7 min-h-[220px]"><Icon size={26} strokeWidth={1.5} className="text-primary mb-8"/><h3 className="font-display text-xl md:text-2xl font-semibold">{title}</h3><p className="text-muted-foreground text-xs md:text-sm leading-6 mt-3">{text}</p></div>)}</div></section>
    <section className="bg-surface py-20 md:py-28"><div className="page-container"><SectionHeading kicker="Where we're rooted" title="Explore by city" description="Kota is home. Our informational content is also accessible to readers across Rajasthan."/><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{cities.map((city,i) => <Link to="/contact" key={city.slug} className={`group border p-7 min-h-[190px] flex flex-col justify-between transition-colors hover:border-primary ${i === 0 ? 'border-primary bg-accent' : 'border-border bg-card'}`}><MapPin size={22} className="text-primary"/><div><p className="font-display text-3xl font-semibold">{city.name}</p><p className="text-muted-foreground text-xs mt-2">{city.description}</p></div></Link>)}</div></div></section>
    <section className="page-container py-20 md:py-28"><SectionHeading kicker="Close to home" title="Kota service areas" description="Local neighborhoods at the heart of our Kota-focused perspective."/><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{serviceAreas.map(area => <div key={area.name} className="border-t border-primary bg-card p-6 min-h-[180px]"><p className="text-primary text-[10px] uppercase tracking-widest">{area.coverage}</p><h3 className="font-display text-2xl mt-5">{area.name}</h3><p className="text-muted-foreground text-sm leading-6 mt-2">{area.description}</p></div>)}</div></section>
    <section className="bg-surface py-20 md:py-28 border-t border-border"><div className="page-container grid lg:grid-cols-2 gap-10 lg:gap-28"><div><p className="eyebrow">Our perspective</p><h2 className="font-display text-4xl md:text-6xl leading-[1.02] font-semibold">Setting the standard for premium gear accessibility.</h2></div><div className="text-muted-foreground leading-8 text-sm md:text-base space-y-5"><p>Good information should feel easy to find. KOTA VAPE SHOP brings a more considered approach to understanding devices, pods, formats, and the details that matter when comparing them.</p><p>Built around Kota, our catalog pairs a carefully edited presentation with authenticity-minded research and approachable general support. It is a place to learn, not an online checkout.</p><Link to="/about" className="inline-flex items-center gap-2 text-primary uppercase text-xs tracking-widest font-semibold">About our research <ArrowUpRight size={16}/></Link></div></div></section>
    <section className="page-container py-20 md:py-28"><div className="border-y border-border py-12 md:py-16 flex flex-col md:flex-row gap-8 md:items-center justify-between"><div className="flex gap-5 items-start"><BookOpen className="text-primary shrink-0 mt-1" size={32}/><div><p className="eyebrow">About our research</p><h2 className="font-display text-3xl md:text-4xl font-semibold">Information with intention.</h2><p className="text-muted-foreground leading-7 max-w-xl mt-3">Technical details, product research, industry context, and authenticity-focused cataloging—presented with clarity for adults exploring the category.</p></div></div><Button asChild className="w-fit shrink-0 uppercase tracking-widest text-xs"><Link to="/about">Learn more <ArrowRight/></Link></Button></div></section>
  </>;
}
