import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight, ChevronDown, Menu, Search, X } from 'lucide-react';

function WhatsAppIcon({ className = 'h-8 w-8' }: { className?: string }) {
  return <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" className={className}><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.297-.347.446-.52.149-.174.198-.298.297-.497.1-.198.05-.371-.025-.52-.074-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 0 1-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 0 1-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 0 1 2.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0 0 12.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 0 0 5.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 0 0-3.48-8.413"/></svg>;
}
import { Button } from '@/components/ui/button';
import { categories } from '@/data/categories';
import { cities } from '@/data/cities';
import { contact } from '@/config/contact';
import logoImage from '@/assets/logo.png';

const consultationMessage = 'Hi, I need expert consultation regarding premium modules.';
const consultationUrl = contact.whatsapp
  ? `https://wa.me/${contact.whatsapp.replace(/\D/g, '')}?text=${encodeURIComponent(consultationMessage)}`
  : null;

export function SiteLayout({ children }: { children: React.ReactNode }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur-xl">
      <div className="mx-auto max-w-7xl px-5 lg:px-8 h-[92px] grid grid-cols-[minmax(0,1fr)_auto] xl:grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-4">
        <Link to="/" className="min-w-0 leading-none group flex items-center" aria-label="Kota Vape Shop home"><img src={logoImage} alt="Kota Vape Shop logo" width={1024} height={1024} className="h-14 w-14 sm:h-16 sm:w-16 object-contain"/></Link>
        <nav aria-label="Main navigation" className="hidden xl:flex min-w-0 items-center justify-center gap-5 text-[11px] font-semibold uppercase tracking-[0.08em]">
          <Link to="/" className="text-muted-foreground hover:text-foreground">Home</Link><Link to="/about" className="text-muted-foreground hover:text-foreground">About us</Link><Link to="/contact" className="text-muted-foreground hover:text-foreground">Contact us</Link><Link to="/shop" search={{ q: '', category: '' }} className="text-muted-foreground hover:text-foreground">Shop</Link>
          <div className="group relative"><Button variant="ghost" size="sm" className="uppercase text-xs">Policy <ChevronDown size={13}/></Button><div className="invisible opacity-0 group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100 absolute top-full left-0 min-w-44 bg-surface border border-border p-2 shadow-xl transition-all"><Link to="/privacy-policy" className="block px-3 py-2.5">Privacy policy</Link><Link to="/terms" className="block px-3 py-2.5">Terms</Link></div></div>
          <div className="group relative"><Button variant="ghost" size="sm" className="uppercase text-xs">Shop by city <ChevronDown size={13}/></Button><div className="invisible opacity-0 group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100 absolute top-full left-0 min-w-44 bg-surface border border-border p-2 shadow-xl transition-all">{cities.map(city => <Link key={city.slug} to="/contact" className="block px-3 py-2.5">{city.name}</Link>)}</div></div>
          <Link to="/replacement-pods" className="text-muted-foreground hover:text-foreground whitespace-nowrap">Replacement pods</Link>
          <div className="group relative"><Button variant="ghost" size="sm" className="uppercase text-xs">Categories <ChevronDown size={13}/></Button><div className="invisible opacity-0 group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100 absolute top-full right-0 min-w-44 bg-surface border border-border p-2 shadow-xl transition-all">{categories.map(category => <Link key={category.slug} to="/shop" search={{ q: '', category: category.name }} className="block px-3 py-2.5 hover:text-primary">{category.name}</Link>)}</div></div>
        </nav>
        <div className="flex shrink-0 items-center gap-1 sm:gap-3"><Button variant="ghost" size="icon" aria-label="Search catalog" onClick={() => setSearchOpen(!searchOpen)}><Search size={19}/></Button><Button variant="ghost" size="icon" className="xl:hidden" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={21}/> : <Menu size={21}/>}</Button></div>
      </div>
      {searchOpen && <form action="/shop" className="border-t border-border p-4 max-w-7xl mx-auto flex gap-2"><input name="q" autoFocus placeholder="Search the catalog..." className="w-full bg-secondary border border-border px-4 py-3 outline-none focus:border-primary text-sm"/><Button type="submit">Search <ArrowRight size={15}/></Button></form>}
      {menuOpen && <nav aria-label="Mobile navigation" className="xl:hidden max-h-[75vh] overflow-y-auto border-t border-border bg-surface px-5 py-4 grid grid-cols-2 gap-1"><Link to="/" onClick={() => setMenuOpen(false)} className="py-3 text-xs uppercase">Home</Link><Link to="/shop" search={{ q: '', category: '' }} onClick={() => setMenuOpen(false)} className="py-3 text-xs uppercase">Shop</Link><Link to="/about" onClick={() => setMenuOpen(false)} className="py-3 text-xs uppercase">About us</Link><Link to="/contact" onClick={() => setMenuOpen(false)} className="py-3 text-xs uppercase">Contact us</Link><Link to="/replacement-pods" onClick={() => setMenuOpen(false)} className="py-3 text-xs uppercase col-span-2">Replacement pods</Link><div className="col-span-2 border-t border-border pt-4 mt-2"><span className="text-primary text-xs uppercase">Categories</span><div className="flex flex-wrap gap-x-5 gap-y-3 py-3">{categories.map(category => <Link key={category.slug} to="/shop" search={{ q: '', category: category.name }} onClick={() => setMenuOpen(false)} className="text-sm text-muted-foreground">{category.name}</Link>)}</div></div><div className="col-span-2 border-t border-border pt-4 mt-2"><Link to="/privacy-policy" onClick={() => setMenuOpen(false)} className="mr-5">Privacy policy</Link><Link to="/terms" onClick={() => setMenuOpen(false)}>Terms</Link></div></nav>}
    </header>
    <main>{children}</main>
    <footer className="bg-surface border-t border-border pt-12 pb-8"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-10 pb-12"><div><h3 className="footer-heading">About Our Research</h3><p className="text-muted-foreground text-sm leading-7">Our platform is dedicated to curating international hardware modules and premium gear for collectors and enthusiasts. Our team leverages technical data from various <span className="text-primary font-semibold">KOTA VAPE SHOP</span> review portals and industry whitepapers to ensure we only catalog original, high-performance gear.</p></div><div><h3 className="footer-heading">Coverage Areas</h3><div className="footer-links"><span>Malviya Nagar, Jaipur</span><span>Gaurav Tower &amp; JLN Marg</span><span>C-Scheme &amp; Civil Lines</span><span>Vaishali Nagar, Jaipur</span></div></div><div><h3 className="footer-heading">Information</h3><div className="footer-links"><Link to="/privacy-policy">Privacy Policy</Link><Link to="/terms">Terms of Consultation</Link><Link to="/about">Authenticity Guides</Link><Link to="/contact">Contact Experts</Link></div></div><div><h3 className="footer-heading">Store Location &amp; Hours</h3><div className="bg-background border border-border border-l-2 border-l-primary p-5 text-sm leading-7"><p className="font-semibold text-foreground">Jaipur Experience Center:</p><p className="text-muted-foreground mt-1">Shop no. A-1, Indira Palace, near Gaurav Tower, D-Block, Crystal Court, Malviya Nagar, Jaipur, Rajasthan - 302017</p><span className="inline-flex items-center gap-2 mt-3 bg-primary/15 text-[#3ecf8e] text-[11px] font-bold uppercase tracking-wide px-3 py-1.5"><span className="h-1.5 w-1.5 rounded-full bg-[#3ecf8e]"></span>Open 24 Hours / 7 Days</span></div></div></div><div className="border-t border-border pt-7 text-xs text-muted-foreground"><span>© {new Date().getFullYear()} KOTA VAPE SHOP. All rights reserved.</span></div></div></footer>
    <aside aria-label="Product consultation" className="fixed bottom-4 left-3 right-[84px] z-40 border border-border border-l-[3px] border-l-primary bg-surface shadow-2xl sm:bottom-5 sm:left-1/2 sm:right-auto sm:w-[min(760px,calc(100vw-180px))] sm:-translate-x-1/2 px-3 py-3 sm:px-5 sm:py-4 lg:flex lg:items-center lg:justify-between lg:gap-5">
      <div className="min-w-0"><p className="text-sm sm:text-base font-semibold leading-snug text-foreground">Looking for a specific Brand or Module?</p><p className="mt-1 text-xs sm:text-sm leading-snug text-muted-foreground">We stock all premium international gear and rare collections. Drop a query and we will arrange it!</p></div>
      <Button asChild className="mt-2 h-9 w-full gap-2 text-xs font-bold uppercase sm:w-auto lg:mt-0 lg:shrink-0 lg:h-11"><a href={consultationUrl ?? '/contact'} target={consultationUrl ? '_blank' : undefined} rel={consultationUrl ? 'noreferrer' : undefined}><WhatsAppIcon className="h-4 w-4"/>Drop a Query</a></Button>
    </aside>
    {consultationUrl ? <a href={consultationUrl} target="_blank" rel="noreferrer" aria-label="Contact on WhatsApp" className="fixed bottom-5 right-5 z-50 grid place-items-center h-14 w-14 lg:h-[72px] lg:w-[72px] rounded-full bg-[#25D366] text-white shadow-[0_8px_24px_rgba(37,211,102,0.45)] hover:scale-105 transition-transform"><WhatsAppIcon className="h-8 w-8 lg:h-11 lg:w-11"/></a> : <Link to="/contact" aria-label="General support contact" className="fixed bottom-5 right-5 z-50 grid place-items-center h-14 w-14 lg:h-[72px] lg:w-[72px] rounded-full bg-[#25D366] text-white shadow-[0_8px_24px_rgba(37,211,102,0.45)] hover:scale-105 transition-transform"><WhatsAppIcon className="h-8 w-8 lg:h-11 lg:w-11"/></Link>}
  </div>;
}
