import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight, ChevronDown, Menu, Search, X, MessageCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { categories } from '@/data/categories';
import { cities } from '@/data/cities';
import { contact } from '@/config/contact';

export function SiteLayout({ children }: { children: React.ReactNode }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  return <div className="min-h-screen bg-background text-foreground">
    <div className="border-b border-border bg-surface text-center text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground py-2.5 px-4">An informational catalog for adults · Product details subject to verification</div>
    <header className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur-xl">
      <div className="mx-auto max-w-7xl px-5 lg:px-8 h-[76px] grid grid-cols-[minmax(0,1fr)_auto] xl:grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-4">
        <Link to="/" className="min-w-0 leading-none group" aria-label="Kota Vape Shop home"><span className="block font-display font-bold text-[21px] sm:text-[25px] tracking-[0.11em] text-foreground">KOTA<span className="text-primary">.</span></span><span className="block text-[9px] tracking-[0.32em] text-primary mt-1.5">VAPE SHOP</span></Link>
        <nav aria-label="Main navigation" className="hidden xl:flex min-w-0 items-center justify-center gap-5 text-[11px] font-semibold uppercase tracking-[0.08em]">
          <Link to="/" className="text-muted-foreground hover:text-foreground">Home</Link><Link to="/about" className="text-muted-foreground hover:text-foreground">About us</Link><Link to="/contact" className="text-muted-foreground hover:text-foreground">Contact us</Link><Link to="/shop" search={{ q: '', category: '' }} className="text-muted-foreground hover:text-foreground">Shop</Link>
          <div className="group relative"><Button variant="ghost" size="sm" className="uppercase text-xs">Policy <ChevronDown size={13}/></Button><div className="invisible opacity-0 group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100 absolute top-full left-0 min-w-44 bg-surface border border-border p-2 shadow-xl transition-all"><Link to="/privacy-policy" className="block px-3 py-2.5">Privacy policy</Link><Link to="/terms" className="block px-3 py-2.5">Terms</Link></div></div>
          <div className="group relative"><Button variant="ghost" size="sm" className="uppercase text-xs">Shop by city <ChevronDown size={13}/></Button><div className="invisible opacity-0 group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100 absolute top-full left-0 min-w-44 bg-surface border border-border p-2 shadow-xl transition-all">{cities.map(city => <Link key={city.slug} to="/contact" className="block px-3 py-2.5">{city.name}</Link>)}</div></div>
          <Link to="/replacement-pods" className="text-muted-foreground hover:text-foreground whitespace-nowrap">Replacement pods</Link>
          <div className="group relative"><Button variant="ghost" size="sm" className="uppercase text-xs">Categories <ChevronDown size={13}/></Button><div className="invisible opacity-0 group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100 absolute top-full right-0 min-w-44 bg-surface border border-border p-2 shadow-xl transition-all">{categories.map(category => <Link key={category.slug} to="/shop" search={{ q: '', category: category.name }} className="block px-3 py-2.5 hover:text-primary">{category.name}</Link>)}</div></div>
        </nav>
        <div className="flex shrink-0 items-center gap-1 sm:gap-3"><Button variant="ghost" size="icon" aria-label="Search catalog" onClick={() => setSearchOpen(!searchOpen)}><Search size={19}/></Button><Button variant="ghost" size="icon" className="xl:hidden" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={21}/> : <Menu size={21}/>}</Button></div>
      </div>
      {searchOpen && <form action="/shop" className="border-t border-border p-4 max-w-7xl mx-auto flex gap-2"><input name="q" autoFocus placeholder="Search the catalog..." className="w-full bg-secondary border border-border px-4 py-3 outline-none focus:border-primary text-sm"/><Button type="submit">Search <ArrowRight size={15}/></Button></form>}
      {menuOpen && <nav aria-label="Mobile navigation" className="xl:hidden max-h-[75vh] overflow-y-auto border-t border-border bg-surface px-5 py-4 grid grid-cols-2 gap-1"><Link to="/" onClick={() => setMenuOpen(false)} className="py-3 text-xs uppercase">Home</Link><Link to="/shop" search={{ q: '', category: '' }} onClick={() => setMenuOpen(false)} className="py-3 text-xs uppercase">Shop</Link><Link to="/about" onClick={() => setMenuOpen(false)} className="py-3 text-xs uppercase">About us</Link><Link to="/contact" onClick={() => setMenuOpen(false)} className="py-3 text-xs uppercase">Contact us</Link><Link to="/replacement-pods" onClick={() => setMenuOpen(false)} className="py-3 text-xs uppercase col-span-2">Replacement pods</Link><div className="col-span-2 border-t border-border pt-4 mt-2"><span className="text-primary text-xs uppercase">Categories</span><div className="flex flex-wrap gap-x-5 gap-y-3 py-3">{categories.map(category => <Link key={category.slug} to="/shop" search={{ q: '', category: category.name }} onClick={() => setMenuOpen(false)} className="text-sm text-muted-foreground">{category.name}</Link>)}</div></div><div className="col-span-2 border-t border-border pt-4 mt-2"><Link to="/privacy-policy" onClick={() => setMenuOpen(false)} className="mr-5">Privacy policy</Link><Link to="/terms" onClick={() => setMenuOpen(false)}>Terms</Link></div></nav>}
    </header>
    <main>{children}</main>
    <footer className="bg-surface border-t border-border pt-20 pb-8"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid grid-cols-2 md:grid-cols-4 gap-10 pb-16"><div className="col-span-2 md:col-span-1"><Link to="/" className="font-display font-bold text-2xl tracking-widest">KOTA<span className="text-primary">.</span></Link><p className="text-primary tracking-[0.25em] text-[10px] mt-2">VAPE SHOP</p><p className="text-muted-foreground text-sm leading-7 mt-6">An adult-focused product information catalog rooted in Kota.</p></div><div><h3 className="footer-heading">Categories</h3><div className="footer-links">{categories.map(category => <Link key={category.slug} to="/shop" search={{ q: '', category: category.name }}>{category.name}</Link>)}<Link to="/replacement-pods">Replacement pods</Link></div></div><div><h3 className="footer-heading">Information</h3><div className="footer-links"><Link to="/about">About us</Link><Link to="/faq">FAQs</Link><Link to="/privacy-policy">Privacy policy</Link><Link to="/terms">Terms</Link><Link to="/contact">Contact</Link></div></div><div><h3 className="footer-heading">Contact</h3><div className="text-sm text-muted-foreground leading-8"><p>{contact.location}</p>{contact.phone && <p>{contact.phone}</p>}{contact.email && <a href={`mailto:${contact.email}`}>{contact.email}</a>}<Link to="/contact" className="flex items-center gap-2 mt-3 text-primary">General inquiries <ArrowRight size={15}/></Link></div></div></div><div className="border-t border-border pt-7 flex flex-col sm:flex-row justify-between gap-4 text-xs text-muted-foreground"><span>© {new Date().getFullYear()} KOTA VAPE SHOP. All rights reserved.</span><span>For adults only · Informational catalog · No online sales</span></div></div></footer>
    {contact.whatsapp ? <a href={`https://wa.me/${contact.whatsapp.replace(/\D/g, '')}?text=${encodeURIComponent('Hello, I have a general question about your catalog.')}`} target="_blank" rel="noreferrer" aria-label="Contact on WhatsApp" className="fixed bottom-6 right-6 z-50 grid place-items-center h-12 w-12 rounded-full bg-primary text-primary-foreground shadow-lg hover:scale-105 transition-transform"><MessageCircle size={22}/></a> : <Link to="/contact" aria-label="General support contact" className="fixed bottom-6 right-6 z-50 grid place-items-center h-12 w-12 rounded-full bg-primary text-primary-foreground shadow-lg hover:scale-105 transition-transform"><MessageCircle size={22}/></Link>}
  </div>;
}
